#!/bin/sh

set -e

TEXFILE="$1"

# Legg inn orddelingspunkt på problematiske ord.  LaTeX deler ikke ord
# med bindestrek automatisk, slik at endel ord blir veldig lange.  Vil
# ikke endre i originalteksten, så vi skriver om aktuelle ord her til
# å inneholde orddelingsmarkør.
sed -i 's%FS/OSS-{}teknologi%FS/OSS-tekno\\-logi%g' $TEXFILE
sed -i 's/-{}opptakeren/-{}opp\\-takeren/g' $TEXFILE
sed -i 's/Eastman-fabrikk/East\\-man-fabrikk/g' $TEXFILE
sed -i 's/TV-{}kringkasting/TV-{}kring\\-kast\\-ing/g' $TEXFILE
sed -i 's/bygningen/byg\\-ningen/g' $TEXFILE
sed -i 's/fildeling/fil\\-del\\-ing/g' $TEXFILE
sed -i 's/fjerdedel/fjerde\\-del/g' $TEXFILE
sed -i 's/ikke-{}diskriminerende/ikke-diskrim\\-inerende/g' $TEXFILE
sed -i 's/kommersiell/kom\\-mer\\-siell/g' $TEXFILE
sed -i 's/nittenhundretalls-advokaten/nitten\\-hundre\\-talls-advokaten/g' $TEXFILE
sed -i 's/skriveferdigheter/skrive\\-ferdig\\-heter/g' $TEXFILE
sed -i 's/tvangslisens/tvangs\\-lisens/g' $TEXFILE
sed -i 's/opphavsrettsvernetid-{}loven/opp\\-havs\\-retts\\-verne\\-tid-{}loven/g' $TEXFILE
sed -i 's/Handels-{}bestemmelsen/Han\\-dels-{}bestem\\-melsen/g' $TEXFILE
sed -i 's/Fremskritts-{}bestemmelsen/Frems\\-kritts-{}bestem\\-melsen/g' $TEXFILE
sed -i 's/programvare-{}bevegelsen/program\\-vare-{}beveg\\-elsen/g' $TEXFILE
sed -i 's/opphavsrettsbeskyttelses-{}system/opp\\-havs\\-retts\\-beskyt\\-telses-{}system/g' $TEXFILE
sed -i 's/anti-{}omgåelsesbestemmelsene/anti-{}om\\-gåelses\\-bestem\\-melsene/g' $TEXFILE
sed -i 's/grunnlovstilleggs/grunn\\-lovs\\-til\\-leggs/g' $TEXFILE
sed -i 's/beslagleggings-{}avsnitt/be\\-slag\\-leg\\-gings-{}av\\-snitt/g' $TEXFILE
sed -i 's/fildelingsnettverk/fil\\-delings\\-nett\\-verk/g' $TEXFILE
sed -i 's/monopol/mono\\-pol/g' $TEXFILE

exit 0
