#!/bin/sh

set -e

TEXFILE="$1"

# Legg inn orddelingspunkt på problematiske ord for å få jevnere
# høyrekant på tekstblokkene.  LaTeX deler ikke ord med bindestrek
# automatisk, slik at endel ord blir veldig lange og stikker ut over
# kanten.  Ønsker ikke endre i originalteksten, så vi skriver om
# aktuelle ord i latex-fila her til å inneholde orddelingsmarkør i
# stedet.
sed -i \
    -e 's/kommersiell/kom\\-mer\\-siell/g' \
    -e 's/piratvirksomhet/pirat\\-virk\\-som\\-het/g' \
    -e 's/skriveferdigheter/skrive\\-ferdig\\-heter/g' \
    -e 's/presidentvalgkampen/president\\-valg\\-kampen/g' \
    -e 's/hovedkvarteret/hoved\\-kvarteret/g' \
    -e 's/søkemotorer/søke\\-motor\\-er/g' \
    -e 's/programmer/prog\\-ram\\-mer/g' \
    -e 's/Johnson/John\\-son/g' \
    -e 's/radiostasjon/radio\\-stasjon/g' \
    -e 's/forfatter/for\\-fat\\-ter/g' \
    -e 's/professor/profes\\-sor/g' \
    -e 's/opphavsrettsvernetid/opp\\-havs\\-retts\\-verne\\-tid/g' \
    -e 's/opphavsrettighetsbeskyttet/opp\\-havs\\-ret\\-tig\\-hets\\-beskyt\\-tet/g' \
    -e 's/bestemmelsen/bestem\\-mel\\-sen/g' \
    -e 's/ /\\thinspace/g' \
    $TEXFILE

exit 0
